# Default application configuration that all configurations inherit from.

scss_files: "**/*.scss"
plugin_directories: ['.scss-linters']

# List of gem names to load custom linters from (make sure they are already
# installed)
plugin_gems: []

linters:
  BangFormat:
    enabled: true
    space_before_bang: true
    space_after_bang: false
    severity: warning

  BemDepth:
    enabled: true
    max_elements: 1
    severity: warning

  BorderZero:
    enabled: true
    convention: zero # or `none`
    severity: warning

  ColorKeyword:
    enabled: true
    severity: warning

  ColorVariable:
    enabled: true
    severity: warning

  Comment:
    enabled: true
    severity: error

  DebugStatement:
    enabled: true
    severity: error

  DeclarationOrder:
    enabled: true
    severity: warning

  DisableLinterReason:
    enabled: false
    severity: warning

  DuplicateProperty:
    enabled: true
    severity: error

  ElsePlacement:
    enabled: true
    style: new_line # or 'same_line'
    severity: error

  EmptyLineBetweenBlocks:
    enabled: true
    ignore_single_line_blocks: true
    severity: warning

  EmptyRule:
    enabled: true
    severity: error

  ExtendDirective:
    enabled: false

  FinalNewline:
    enabled: true
    present: true
    severity: warning

  HexLength:
    enabled: true
    style: long # or 'short'
    severity: warning

  HexNotation:
    enabled: true
    style: lowercase # or 'uppercase'
    severity: warning

  HexValidation:
    enabled: true
    severity: warning

  IdSelector:
    enabled: true
    severity: error

  ImportantRule:
    enabled: true
    severity: warning

  ImportPath:
    enabled: true
    leading_underscore: false
    filename_extension: false
    severity: error

  Indentation:
    enabled: true
    allow_non_nested_indentation: true
    character: space # or 'tab'
    width: 4

  LeadingZero:
    enabled: true
    style: include_zero # or 'exclude_zero'
    severity: warning

  MergeableSelector:
    enabled: true
    force_nesting: true
    severity: error

  NameFormat:
    enabled: true
    allow_leading_underscore: true
    convention: hyphenated_lowercase # or 'camel_case', or 'snake_case', or a regex pattern

  NestingDepth:
    enabled: true
    max_depth: 3
    ignore_parent_selectors: false
    severity: warning

  PlaceholderInExtend:
    enabled: true
    severity: error

  PropertyCount:
    enabled: false
    include_nested: false
    max_properties: 10

  PropertySortOrder:
    enabled: false
    ignore_unspecified: false
    min_properties: 2
    separate_groups: false

  PropertySpelling:
    enabled: true
    extra_properties: []
    severity: error

  PropertyUnits:
    enabled: true
    global: [
      'ch', 'em', 'ex', 'rem',                 # Font-relative lengths
      'cm', 'in', 'mm', 'pc', 'pt', 'px', 'q', # Absolute lengths
      'vh', 'vw', 'vmin', 'vmax',              # Viewport-percentage lengths
      'deg', 'grad', 'rad', 'turn',            # Angle
      'ms', 's',                               # Duration
      'Hz', 'kHz',                             # Frequency
      'dpi', 'dpcm', 'dppx',                   # Resolution
      '%']                                     # Other
    properties: {}
    severity: error

  PseudoElement:
    enabled: true
    severity: warning

  QualifyingElement:
    enabled: true
    allow_element_with_attribute: true
    allow_element_with_class: false
    allow_element_with_id: false
    severity: error

  SelectorDepth:
    enabled: true
    max_depth: 3
    severity: warning

  SelectorFormat:
    enabled: true
    convention: hyphenated_BEM # or 'hyphenated_lowercase, or' 'strict_BEM', or 'snake_case', or 'camel_case', or a regex pattern

  Shorthand:
    enabled: true
    allowed_shorthands: [1, 2, 3]
    severity: warning

  SingleLinePerProperty:
    enabled: true
    allow_single_line_rule_sets: true
    severity: error

  SingleLinePerSelector:
    enabled: true
    severity: error

  SpaceAfterComma:
    enabled: true
    style: one_space # or 'no_space', or 'at_least_one_space'
    severity: error

  SpaceAfterPropertyColon:
    enabled: true
    style: one_space # or 'no_space', or 'at_least_one_space', or 'aligned'
    severity: error

  SpaceAfterPropertyName:
    enabled: true
    severity: error

  SpaceAfterVariableName:
    enabled: true
    severity: error

  SpaceAroundOperator:
    enabled: true
    style: one_space # or 'no_space'
    severity: error

  SpaceBeforeBrace:
    enabled: true
    style: space # or 'new_line'
    allow_single_line_padding: false
    severity: error

  SpaceBetweenParens:
    enabled: true
    spaces: 0
    severity: warning

  StringQuotes:
    enabled: true
    style: single_quotes # or double_quotes
    severity: error

  TrailingSemicolon:
    enabled: true
    severity: error

  TrailingWhitespace:
    enabled: false
    severity: warning

  TrailingZero:
    enabled: true
    severity: warning

  TransitionAll:
    enabled: true
    severity: warning

  UnnecessaryMantissa:
    enabled: true
    severity: warning

  UnnecessaryParentReference:
    enabled: true
    severity: warning

  UrlFormat:
    enabled: false

  UrlQuotes:
    enabled: true
    severity: warning

  VariableForProperty:
    enabled: false
    properties: []

  VendorPrefix:
    enabled: true
    identifier_list: base
    additional_identifiers: []
    excluded_identifiers: []
    severity: warning

  ZeroUnit:
    enabled: true
    severity: error

  Compass::*:
    enabled: false
